{{ if and .Values.persistence.enabled (not .Values.databasePVC.existingClaimName) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fullname" . }}-{{ .Values.databasePVC.name}}
  labels:
    app: "{{ template "fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  {{- if .Values.persistence.useDynamicProvisioning }}
  ## if present, use the storageClassName from the values.yaml, else use the
  ## default storageClass setup by kube Administrator
  ##
  ## setting storageClassName to nil means use the default storage class
  storageClassName: {{ default nil .Values.databasePVC.storageClassName | quote }}
  {{- else }}
  ## disable dynamic provisioning
  storageClassName: ""
  {{- end }}

  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.databasePVC.size | quote }}
{{- end }}
