apiVersion: v1
description: Cloudant for Linux.
home: https://www.ibm.com/analytics/us/en/technology/cloud-data-services/cloudant/
icon: https://pbs.twimg.com/profile_images/618444507042988041/r72YruBL.png
keywords:
- cloudant
- IBM
- database
maintainers:
- name: IBM
name: ibm-cloudant-dev
tillerVersion: '>=2.4.0'
version: 1.0.3
