# Specify architecture (amd64, ppc64le, s390x) and weight to be  used for scheduling as follows :
#   0 - Do not use
#   1 - Least preferred
#   2 - No preference
#   3 - Most preferred
arch:
  amd64: "3 - Most preferred"
  ppc64le: "2 - No preference"
  s390x: "2 - No preference"


## image parameters
image:
  repository: ibmcom/cloudant-developer
  tag: latest
  pullPolicy: Always
initImage:
  repository: "ibmcom/icp-initcontainer"
  tag: "1.0.0"

## global persistence parameters
persistence:
  enabled: true
  useDynamicProvisioning: false

databasePVC:
  name: "cloudant-pvc"
  ## specify the storageClassName you want to use
  ## if you don't specify a storageClassName it will use the default
  storageClassName: ""
  ## Specify the name of the Existing Claim to be used by your application
  ## empty string means don't use an existClaim
  existingClaimName: ""
  size: 3Gi

## database parameters
database:
  readinessProbePeriodSeconds: 2
  readinessProbeInitialDelaySeconds: 30
  livenessProbePeriodSeconds: 2
  livenessProbeInitialDelaySeconds: 200
